# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd25c7b2833dfe6defcfaec5948ab5293f93a53f849fec191ca1bec8bf0650a138aee3517d14ea47b160778b024e8fd5ca4fc2ffc3fba23be01e5a2efd32631b

test:
  secret_key_base: 30c383bc35ad821d62b1e2e818a38b5094cf882eed32b4122429fc0aa93f1c9a546b1fb6d504edbf0a8ce3afed53ff8f53615882268d630803d97f607b737a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
